# name: CI
# on: [push]
# jobs:
#   theme-check:
#     name: Theme Check
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Theme Check
#         uses: shopify/theme-check-action@v2
#         with:
#           token: ${{ github.token }}

name: CI

on:
  pull_request:
    branches: [header-section]  # or your target branch

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

